name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
        # 1. change path which exist lib/main.dart
        #working-directory: ./davis13319.github.io
      # 2. change path to [existed lib/main.dart path]/build/web
      - run: cd ./build/web
      - run: git init
      # 3. change your email
      - run: git config --global user.email davis13319@gmail.com
      # 4. change your name
      - run: git config --global user.name davis13319
      - run: git status
      # 5. change your repository
      #- run: git remote add origin https://${{secrets.commit_secret}}@github.com/davis13319/davis13319.github.io.git #최초 한번만 시행해야되서 막음
      - run: git checkout -b gh-pages
      - run: git add --all
      - run: git commit -m "update"
      - run: git push origin gh-pages -f